.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH snip-init 1  "snip 0.3.0" 
.SH NAME
snip\-init \- Create a new filesystem snippet library
.SH SYNOPSIS
\fBsnip init\fR [\fB\-\-library\fR] [\fB\-\-name\fR] [\fB\-\-git\fR] [\fB\-\-output\fR] [\fB\-\-color\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Create a new filesystem snippet library
.SH OPTIONS
.TP
\fB\-\-library\fR \fI<LIBRARY>\fR
Library root. Falls back to SNIP_LIBRARY, ancestor discovery, then config
.TP
\fB\-\-name\fR \fI<NAME>\fR

.TP
\fB\-\-git\fR
Initialize a dedicated Git repository after creating the library
.TP
\fB\-\-output\fR \fI<OUTPUT>\fR
Structured output mode for commands that return records
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
human
.IP \(bu 2
json
.IP \(bu 2
jsonl
.RE
.TP
\fB\-\-color\fR \fI<COLOR>\fR
Color policy for terminal preview
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
auto
.IP \(bu 2
always
.IP \(bu 2
never
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: .]

