.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH snip-path 1  "snip 0.5.5" 
.SH NAME
snip\-path \- Print a managed filesystem path
.SH SYNOPSIS
\fBsnip path\fR [\fB\-\-library\fR] [\fB\-\-metadata\fR] [\fB\-\-output\fR] [\fB\-\-readme\fR] [\fB\-\-color\fR] [\fB\-\-fragment\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISELECTOR\fR> 
.SH DESCRIPTION
Print a managed filesystem path
.SH OPTIONS
.TP
\fB\-\-library\fR \fI<LIBRARY>\fR
Library root. Falls back to SNIP_LIBRARY, ancestor discovery, then config
.TP
\fB\-\-metadata\fR

.TP
\fB\-\-output\fR \fI<OUTPUT>\fR
Structured output mode for commands that return records
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
human
.IP \(bu 2
json
.IP \(bu 2
jsonl
.RE
.TP
\fB\-\-readme\fR

.TP
\fB\-\-color\fR \fI<COLOR>\fR
Color policy for terminal preview
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
auto
.IP \(bu 2
always
.IP \(bu 2
never
.RE
.TP
\fB\-\-fragment\fR \fI<FRAGMENT>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISELECTOR\fR>

