.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH snip-fragment-edit 1  "snip 0.5.5" 
.SH NAME
snip\-fragment\-edit
.SH SYNOPSIS
\fBsnip fragment edit\fR [\fB\-\-library\fR] [\fB\-\-title\fR] [\fB\-\-language\fR] [\fB\-\-output\fR] [\fB\-\-color\fR] [\fB\-\-content\fR] [\fB\-\-content\-file\fR] [\fB\-\-simplified\-ui\fR] [\fB\-\-note\fR] [\fB\-\-note\-file\fR] [\fB\-\-clear\-note\fR] [\fB\-\-if\-hash\fR] [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISELECTOR\fR> <\fIFRAGMENT\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-library\fR \fI<LIBRARY>\fR
Library root. Falls back to SNIP_LIBRARY, ancestor discovery, then config
.TP
\fB\-\-title\fR \fI<TITLE>\fR

.TP
\fB\-\-language\fR \fI<LANGUAGE>\fR

.TP
\fB\-\-output\fR \fI<OUTPUT>\fR
Structured output mode for commands that return records
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
human
.IP \(bu 2
json
.IP \(bu 2
jsonl
.RE
.TP
\fB\-\-color\fR \fI<COLOR>\fR
Color policy for terminal preview
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
auto
.IP \(bu 2
always
.IP \(bu 2
never
.RE
.TP
\fB\-\-content\fR \fI<CONTENT>\fR
Replacement fragment content, given inline
.TP
\fB\-\-content\-file\fR \fI<CONTENT_FILE>\fR

.TP
\fB\-\-simplified\-ui\fR[=\fI<BOOL>\fR]
Use square TUI bars without Powerline font glyphs for this run
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
true
.IP \(bu 2
false
.RE
.TP
\fB\-\-note\fR \fI<NOTE>\fR
Replacement fragment note (Markdown), given inline
.TP
\fB\-\-note\-file\fR \fI<NOTE_FILE>\fR

.TP
\fB\-\-clear\-note\fR

.TP
\fB\-\-if\-hash\fR \fI<IF_HASH>\fR

.TP
\fB\-\-force\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISELECTOR\fR>

.TP
<\fIFRAGMENT\fR>

