.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH snip-man-install 1  "snip 0.5.3" 
.SH NAME
snip\-man\-install \- Install all manual pages
.SH SYNOPSIS
\fBsnip man install\fR [\fB\-\-library\fR] [\fB\-\-prefix\fR] [\fB\-\-force\fR] [\fB\-\-output\fR] [\fB\-\-color\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Install all manual pages
.SH OPTIONS
.TP
\fB\-\-library\fR \fI<LIBRARY>\fR
Library root. Falls back to SNIP_LIBRARY, ancestor discovery, then config
.TP
\fB\-\-prefix\fR \fI<PREFIX>\fR
Install below PREFIX/share instead of the user data directory
.TP
\fB\-\-force\fR
Replace pages not recorded in snip\*(Aqs installation manifest
.TP
\fB\-\-output\fR \fI<OUTPUT>\fR
Structured output mode for commands that return records
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
human
.IP \(bu 2
json
.IP \(bu 2
jsonl
.RE
.TP
\fB\-\-color\fR \fI<COLOR>\fR
Color policy for terminal preview
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
auto
.IP \(bu 2
always
.IP \(bu 2
never
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
