// @generated by examples/generate-themes.rs; do not edit by hand.

#[rustfmt::skip]
pub static THEMES: &[(&str, &str)] = &[
    ("dark-ayu", include_str!("../../assets/themes/dark-ayu.toml")),
    ("dark-catppuccin", include_str!("../../assets/themes/dark-catppuccin.toml")),
    ("dark-default", include_str!("../../assets/themes/dark-default.toml")),
    ("dark-dracula", include_str!("../../assets/themes/dark-dracula.toml")),
    ("dark-everforest", include_str!("../../assets/themes/dark-everforest.toml")),
    ("dark-gruvbox", include_str!("../../assets/themes/dark-gruvbox.toml")),
    ("dark-nord", include_str!("../../assets/themes/dark-nord.toml")),
    ("dark-onedark", include_str!("../../assets/themes/dark-onedark.toml")),
    ("dark-solarized", include_str!("../../assets/themes/dark-solarized.toml")),
    ("dark-tokyonight", include_str!("../../assets/themes/dark-tokyonight.toml")),
    ("light-ayu", include_str!("../../assets/themes/light-ayu.toml")),
    ("light-catppuccin", include_str!("../../assets/themes/light-catppuccin.toml")),
    ("light-default", include_str!("../../assets/themes/light-default.toml")),
    ("light-everforest", include_str!("../../assets/themes/light-everforest.toml")),
    ("light-github", include_str!("../../assets/themes/light-github.toml")),
    ("light-gruvbox", include_str!("../../assets/themes/light-gruvbox.toml")),
    ("light-solarized", include_str!("../../assets/themes/light-solarized.toml")),
];
