use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use snip::theme::{self, ThemeColor, base16, surface, validate};

const GENERATED: &str = "# @generated by examples/generate-themes.rs; do not edit by hand.\n";

#[derive(Clone, Copy)]
struct ThemeSpec {
    output: &'static str,
    input: &'static str,
    source: &'static str,
    syntax: Option<&'static str>,
}

const SPECS: &[ThemeSpec] = &[
    ThemeSpec {
        output: "dark-dracula",
        input: "dracula",
        source: "dracula",
        syntax: Some("Dracula"),
    },
    ThemeSpec {
        output: "dark-gruvbox",
        input: "gruvbox-dark-medium",
        source: "gruvbox-dark-medium",
        syntax: Some("GruvboxDark"),
    },
    ThemeSpec {
        output: "light-gruvbox",
        input: "gruvbox-light-medium",
        source: "gruvbox-light-medium",
        syntax: Some("GruvboxLight"),
    },
    ThemeSpec {
        output: "dark-nord",
        input: "nord",
        source: "nord",
        syntax: Some("Nord"),
    },
    ThemeSpec {
        output: "dark-everforest",
        input: "everforest",
        source: "everforest",
        syntax: None,
    },
    ThemeSpec {
        output: "light-everforest",
        input: "everforest-light",
        source: "everforest-light-medium",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-ayu",
        input: "ayu-dark",
        source: "ayu-dark",
        syntax: None,
    },
    ThemeSpec {
        output: "light-ayu",
        input: "ayu-light",
        source: "ayu-light",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-catppuccin",
        input: "catppuccin-mocha",
        source: "catppuccin-mocha",
        syntax: Some("CatppuccinMocha"),
    },
    ThemeSpec {
        output: "light-catppuccin",
        input: "catppuccin-latte",
        source: "catppuccin-latte",
        syntax: Some("CatppuccinLatte"),
    },
    ThemeSpec {
        output: "dark-solarized",
        input: "solarized-dark",
        source: "solarized-dark",
        syntax: Some("SolarizedDark"),
    },
    ThemeSpec {
        output: "light-solarized",
        input: "solarized-light",
        source: "solarized-light",
        syntax: Some("SolarizedLight"),
    },
    ThemeSpec {
        output: "dark-onedark",
        input: "onedark",
        source: "onedark",
        syntax: Some("TwoDark"),
    },
    ThemeSpec {
        output: "light-github",
        input: "github",
        source: "github",
        syntax: Some("Github"),
    },
    ThemeSpec {
        output: "dark-tokyonight",
        input: "tokyo-night-dark",
        source: "tokyo-night-dark",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-kanagawa",
        input: "kanagawa",
        source: "kanagawa",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-edge",
        input: "edge-dark",
        source: "edge-dark",
        syntax: None,
    },
    ThemeSpec {
        output: "light-edge",
        input: "edge-light",
        source: "edge-light",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-horizon",
        input: "horizon-dark",
        source: "horizon-dark",
        syntax: None,
    },
    ThemeSpec {
        output: "light-horizon",
        input: "horizon-light",
        source: "horizon-light",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-primer",
        input: "primer-dark",
        source: "primer-dark",
        syntax: None,
    },
    ThemeSpec {
        output: "light-primer",
        input: "primer-light",
        source: "primer-light",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-selenized",
        input: "selenized-dark",
        source: "selenized-dark",
        syntax: None,
    },
    ThemeSpec {
        output: "light-selenized",
        input: "selenized-light",
        source: "selenized-light",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-tokyonight-storm",
        input: "tokyo-night-storm",
        source: "tokyo-night-storm",
        syntax: None,
    },
    ThemeSpec {
        output: "light-tokyonight",
        input: "tokyo-night-light",
        source: "tokyo-night-light",
        syntax: None,
    },
];

#[derive(Clone, Copy)]
struct CuratedSpec {
    output: &'static str,
    assumed_canvas: &'static str,
}

const CURATED_SPECS: &[CuratedSpec] = &[
    CuratedSpec {
        output: "dark-default",
        assumed_canvas: "#0d1117",
    },
    CuratedSpec {
        output: "light-default",
        assumed_canvas: "#ffffff",
    },
    CuratedSpec {
        output: "light-teal",
        assumed_canvas: "#ffffff",
    },
];

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let arguments = env::args().skip(1).collect::<Vec<_>>();
    if let Some(position) = arguments.iter().position(|argument| argument == "--audit") {
        let directory = arguments
            .get(position + 1)
            .ok_or_else(|| "--audit requires a directory".to_owned())?;
        return audit(Path::new(directory));
    }
    let check = arguments.iter().any(|argument| argument == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let mut generated = BTreeMap::new();
    for spec in SPECS {
        let path = root.join(format!("assets/base16/{}.yaml", spec.input));
        let text = fs::read_to_string(&path)
            .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
        let scheme = base16::parse_scheme(&text)
            .map_err(|error| format!("cannot parse {}: {error}", path.display()))?;
        let theme = base16::scheme_to_theme(
            &scheme,
            spec.output,
            &format!("base16:{}", spec.source),
            spec.syntax,
        )
        .map_err(|error| error.to_string())?;
        generated.insert(
            root.join(format!("assets/themes/{}.toml", spec.output)),
            format!(
                "{GENERATED}{}",
                theme::to_toml(&theme).map_err(|error| error.to_string())?
            ),
        );
    }
    for spec in CURATED_SPECS {
        let theme = curated_theme(&root, spec)?;
        generated.insert(
            root.join(format!("assets/themes/{}.toml", spec.output)),
            format!(
                "{GENERATED}{}",
                theme::to_toml(&theme).map_err(|error| error.to_string())?
            ),
        );
    }
    generated.insert(root.join("src/theme/builtin.rs"), render_builtin());

    let mut drift = Vec::new();
    for (path, expected) in generated {
        if check {
            match fs::read_to_string(&path) {
                Ok(actual) if actual == expected => {}
                Ok(actual) => drift.push(format!(
                    "{} differs (disk {} bytes, generated {} bytes)",
                    path.display(),
                    actual.len(),
                    expected.len()
                )),
                Err(error) => {
                    drift.push(format!("{} missing or unreadable: {error}", path.display()))
                }
            }
        } else {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
            }
            fs::write(&path, expected)
                .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
        }
    }
    if drift.is_empty() {
        Ok(())
    } else {
        Err(format!("generated theme drift:\n{}", drift.join("\n")))
    }
}

fn curated_theme(root: &Path, spec: &CuratedSpec) -> Result<theme::Theme, String> {
    let path = root.join(format!("assets/theme-sources/{}.toml", spec.output));
    let mut theme = theme::parse_file(&path)
        .map_err(|error| format!("cannot parse {}: {error}", path.display()))?;
    let assumed_canvas = ThemeColor::parse(spec.assumed_canvas, "assumed_canvas")
        .map_err(|error| error.to_string())?;
    let surfaces =
        surface::derive_bar_pill_surfaces(theme.ui.bar_bg, assumed_canvas, theme.appearance)
            .map_err(|error| format!("cannot derive {} surfaces: {error}", spec.output))?;
    theme.ui.bar_bg = surfaces.bar_bg;
    theme.ui.pill_secondary = surfaces.pill_secondary;
    Ok(theme)
}

fn render_builtin() -> String {
    let mut names = SPECS
        .iter()
        .map(|spec| spec.output)
        .chain(CURATED_SPECS.iter().map(|spec| spec.output))
        .collect::<Vec<_>>();
    names.sort_unstable();
    let mut output = "// @generated by examples/generate-themes.rs; do not edit by hand.\n\n#[rustfmt::skip]\npub static THEMES: &[(&str, &str)] = &[\n".to_owned();
    for name in names {
        output.push_str(&format!(
            "    ({name:?}, include_str!(\"../../assets/themes/{name}.toml\")),\n"
        ));
    }
    output.push_str("];\n");
    output
}

fn audit(directory: &Path) -> Result<(), String> {
    let mut paths = fs::read_dir(directory)
        .map_err(|error| format!("cannot read {}: {error}", directory.display()))?
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|extension| extension.to_str()) == Some("yaml"))
        .collect::<Vec<_>>();
    paths.sort_by_key(|path| path.file_name().map(|name| name.to_os_string()));
    let mut counts = [0_u32; 4];
    for path in paths {
        let stem = path
            .file_stem()
            .and_then(|value| value.to_str())
            .unwrap_or("scheme");
        let probe_name = sanitized_name(stem)
            .filter(|name| theme::validate_theme_name(name).is_ok())
            .unwrap_or_else(|| "scheme".to_owned());
        let result = fs::read_to_string(&path)
            .map_err(|error| error.to_string())
            .and_then(|text| base16::parse_scheme(&text).map_err(|error| error.to_string()))
            .and_then(|scheme| {
                base16::scheme_to_theme(&scheme, &probe_name, &format!("base16:{stem}"), None)
                    .map_err(|error| error.to_string())
            });
        match result {
            Err(error) => {
                counts[3] += 1;
                println!("error\t{stem}\t-\t{error}");
            }
            Ok(theme) => {
                let checks = validate::check(&theme);
                let has_fail = checks
                    .iter()
                    .any(|check| check.level == validate::Level::Fail);
                let has_warn = checks
                    .iter()
                    .any(|check| check.level == validate::Level::Warn);
                let (status, count) = if has_fail {
                    ("fail", 2)
                } else if has_warn {
                    ("warn", 1)
                } else {
                    ("pass", 0)
                };
                counts[count] += 1;
                let findings = checks
                    .iter()
                    .filter(|check| {
                        !matches!(check.level, validate::Level::Ok | validate::Level::Note)
                    })
                    .map(|check| format!("{} ({})", check.id, check.detail))
                    .collect::<Vec<_>>();
                println!(
                    "{status}\t{stem}\t{}\t{}",
                    theme.appearance.as_str(),
                    if findings.is_empty() {
                        "-".to_owned()
                    } else {
                        findings.join("; ")
                    }
                );
            }
        }
    }
    let total = counts.iter().sum::<u32>();
    eprintln!(
        "{} pass, {} warn, {} fail, {} error, {total} total",
        counts[0], counts[1], counts[2], counts[3]
    );
    Ok(())
}

fn sanitized_name(stem: &str) -> Option<String> {
    let name = stem.to_ascii_lowercase().replace(['_', ' '], "-");
    let name = name.trim_matches('-').to_owned();
    (!name.is_empty()).then_some(name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use snip::theme::color::contrast;

    #[test]
    fn curated_sources_generate_terminal_themes_with_the_shared_surface_floors() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        for spec in CURATED_SPECS {
            let theme = curated_theme(&root, spec).unwrap();
            let canvas = ThemeColor::parse(spec.assumed_canvas, "assumed_canvas").unwrap();

            assert_eq!(theme.ui.background, ThemeColor::Terminal);
            assert_eq!(theme.ui.foreground, ThemeColor::Terminal);
            assert!(contrast(theme.ui.bar_bg, canvas).unwrap() >= surface::BAR_CONTRAST_FLOOR);
            assert!(
                contrast(theme.ui.pill_secondary, theme.ui.bar_bg).unwrap()
                    >= surface::PILL_CONTRAST_FLOOR
            );
        }
    }

    #[test]
    fn builtin_index_contains_every_generated_theme() {
        let index = render_builtin();
        for name in SPECS
            .iter()
            .map(|spec| spec.output)
            .chain(CURATED_SPECS.iter().map(|spec| spec.output))
        {
            assert!(index.contains(&format!("({name:?}, include_str!")));
        }
    }
}
