use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

const GENERATED: &str = "# @generated by examples/generate-themes.rs; do not edit by hand.\n";

#[derive(Clone, Copy)]
struct ThemeSpec {
    output: &'static str,
    input: &'static str,
    source: &'static str,
    syntax: Option<&'static str>,
}

const SPECS: &[ThemeSpec] = &[
    ThemeSpec {
        output: "dark-dracula",
        input: "dracula",
        source: "dracula",
        syntax: Some("Dracula"),
    },
    ThemeSpec {
        output: "dark-gruvbox",
        input: "gruvbox-dark-medium",
        source: "gruvbox-dark-medium",
        syntax: Some("GruvboxDark"),
    },
    ThemeSpec {
        output: "light-gruvbox",
        input: "gruvbox-light-medium",
        source: "gruvbox-light-medium",
        syntax: Some("GruvboxLight"),
    },
    ThemeSpec {
        output: "dark-nord",
        input: "nord",
        source: "nord",
        syntax: Some("Nord"),
    },
    ThemeSpec {
        output: "dark-everforest",
        input: "everforest",
        source: "everforest",
        syntax: None,
    },
    ThemeSpec {
        output: "light-everforest",
        input: "everforest-light",
        source: "everforest-light-medium",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-ayu",
        input: "ayu-dark",
        source: "ayu-dark",
        syntax: None,
    },
    ThemeSpec {
        output: "light-ayu",
        input: "ayu-light",
        source: "ayu-light",
        syntax: None,
    },
    ThemeSpec {
        output: "dark-catppuccin",
        input: "catppuccin-mocha",
        source: "catppuccin-mocha",
        syntax: Some("CatppuccinMocha"),
    },
    ThemeSpec {
        output: "light-catppuccin",
        input: "catppuccin-latte",
        source: "catppuccin-latte",
        syntax: Some("CatppuccinLatte"),
    },
    ThemeSpec {
        output: "dark-solarized",
        input: "solarized-dark",
        source: "solarized-dark",
        syntax: Some("SolarizedDark"),
    },
    ThemeSpec {
        output: "light-solarized",
        input: "solarized-light",
        source: "solarized-light",
        syntax: Some("SolarizedLight"),
    },
    ThemeSpec {
        output: "dark-onedark",
        input: "onedark",
        source: "onedark",
        syntax: Some("TwoDark"),
    },
    ThemeSpec {
        output: "light-github",
        input: "github",
        source: "github",
        syntax: Some("Github"),
    },
    ThemeSpec {
        output: "dark-tokyonight",
        input: "tokyo-night-dark",
        source: "tokyo-night-dark",
        syntax: None,
    },
];

#[derive(Deserialize)]
struct Scheme {
    name: String,
    variant: Option<String>,
    palette: BTreeMap<String, String>,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let check = env::args().skip(1).any(|argument| argument == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let mut generated = BTreeMap::new();
    for spec in SPECS {
        let path = root.join(format!("assets/base16/{}.yaml", spec.input));
        let text = fs::read_to_string(&path)
            .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
        let scheme: Scheme = serde_norway::from_str(&text)
            .map_err(|error| format!("cannot parse {}: {error}", path.display()))?;
        validate_palette(spec.source, &scheme.palette)?;
        generated.insert(
            root.join(format!("assets/themes/{}.toml", spec.output)),
            render_theme(*spec, &scheme)?,
        );
    }
    generated.insert(root.join("src/theme/builtin.rs"), render_builtin());

    let mut drift = Vec::new();
    for (path, expected) in generated {
        if check {
            match fs::read_to_string(&path) {
                Ok(actual) if actual == expected => {}
                Ok(actual) => drift.push(format!(
                    "{} differs (disk {} bytes, generated {} bytes)",
                    path.display(),
                    actual.len(),
                    expected.len()
                )),
                Err(error) => {
                    drift.push(format!("{} missing or unreadable: {error}", path.display()))
                }
            }
        } else {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
            }
            fs::write(&path, expected)
                .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
        }
    }
    if drift.is_empty() {
        Ok(())
    } else {
        Err(format!("generated theme drift:\n{}", drift.join("\n")))
    }
}

fn render_theme(spec: ThemeSpec, scheme: &Scheme) -> Result<String, String> {
    let p = &scheme.palette;
    let selection_bg = color(p, "base02")?;
    let candidates = ["base00", "base05", "base06", "base07"];
    let mut best = candidates[0];
    let mut best_contrast = -1.0;
    for candidate in candidates {
        let value = contrast(parse_rgb(color(p, candidate)?)?, parse_rgb(selection_bg)?);
        if value > best_contrast {
            best = candidate;
            best_contrast = value;
        }
    }
    if best_contrast < 4.5 {
        return Err(format!(
            "scheme {}: selection contrast {best_contrast:.2} < 4.5",
            spec.source
        ));
    }
    let appearance = match scheme.variant.as_deref() {
        Some("light") => "light",
        Some("dark") => "dark",
        Some(other) => return Err(format!("scheme {}: invalid variant {other}", spec.source)),
        None => {
            if luminance(parse_rgb(color(p, "base00")?)?) < 0.5 {
                "dark"
            } else {
                "light"
            }
        }
    };
    let roles = [
        ("background", "base00"),
        ("foreground", "base05"),
        ("accent", "base0D"),
        ("accent_alt", "base0E"),
        ("border", "base03"),
        ("muted", "base04"),
        ("selection_bg", "base02"),
        ("selection_fg", best),
        ("retained_bg", "base01"),
        ("pill_primary", "base0C"),
        ("pill_secondary", "base03"),
        ("bar_bg", "base01"),
        ("bar_fg", "base05"),
        ("tag", "base09"),
        ("rule", "base02"),
        ("success", "base0B"),
        ("warning", "base0A"),
        ("error", "base08"),
    ];
    let mut output = format!(
        "{GENERATED}schema_version = 1\nname = {:?}\ndisplay_name = {:?}\nappearance = {:?}\nsource = {:?}\n\n[ui]\n",
        spec.output,
        scheme.name,
        appearance,
        format!("base16:{}", spec.source)
    );
    let background = color(p, "base00")?;
    let bar_background = color(p, "base01")?;
    for (role, slot) in roles {
        let mapped = color(p, slot)?;
        let reference = if role == "bar_fg" {
            bar_background
        } else {
            background
        };
        let value = match role {
            "muted" | "bar_fg" | "tag" | "accent" | "accent_alt" | "warning" | "error"
            | "success" => ensure_contrast(mapped, reference, 4.5)?,
            "rule" => ensure_contrast(mapped, reference, 3.0)?,
            "border" => ensure_contrast(mapped, reference, 2.5)?,
            _ => mapped.to_owned(),
        };
        output.push_str(&format!("{role} = {value:?}\n"));
    }
    output.push_str("\n[syntax]\n");
    match spec.syntax {
        Some(theme) => output.push_str(&format!("theme = {theme:?}\n")),
        None => output.push_str("derive = \"base16\"\n"),
    }
    output.push_str("\n[palette]\n");
    for index in 0..16 {
        let key = format!("base{index:02X}");
        output.push_str(&format!("{key} = {:?}\n", color(p, &key)?));
    }
    Ok(output)
}

fn render_builtin() -> String {
    let mut names = SPECS
        .iter()
        .map(|spec| spec.output)
        .chain(["dark-default", "light-default"])
        .collect::<Vec<_>>();
    names.sort_unstable();
    let mut output =
        "// @generated by examples/generate-themes.rs; do not edit by hand.\n\n#[rustfmt::skip]\npub static THEMES: &[(&str, &str)] = &[\n"
            .to_owned();
    for name in names {
        output.push_str(&format!(
            "    ({name:?}, include_str!(\"../../assets/themes/{name}.toml\")),\n"
        ));
    }
    output.push_str("];\n");
    output
}

fn validate_palette(slug: &str, palette: &BTreeMap<String, String>) -> Result<(), String> {
    if palette.len() != 16 {
        return Err(format!(
            "scheme {slug}: palette must contain exactly 16 colors"
        ));
    }
    for index in 0..16 {
        let key = format!("base{index:02X}");
        let value = color(palette, &key)?;
        parse_rgb(value).map_err(|error| format!("scheme {slug}: {error}"))?;
    }
    Ok(())
}

fn color<'a>(palette: &'a BTreeMap<String, String>, key: &str) -> Result<&'a str, String> {
    palette
        .get(key)
        .map(String::as_str)
        .ok_or_else(|| format!("missing palette key {key}"))
}

fn parse_rgb(value: &str) -> Result<[u8; 3], String> {
    let hex = value
        .strip_prefix('#')
        .filter(|hex| hex.len() == 6)
        .ok_or_else(|| format!("invalid #rrggbb color {value}"))?;
    Ok([
        u8::from_str_radix(&hex[0..2], 16).map_err(|_| format!("invalid #rrggbb color {value}"))?,
        u8::from_str_radix(&hex[2..4], 16).map_err(|_| format!("invalid #rrggbb color {value}"))?,
        u8::from_str_radix(&hex[4..6], 16).map_err(|_| format!("invalid #rrggbb color {value}"))?,
    ])
}

fn luminance(rgb: [u8; 3]) -> f64 {
    let channel = |value: u8| {
        let value = f64::from(value) / 255.0;
        if value <= 0.04045 {
            value / 12.92
        } else {
            ((value + 0.055) / 1.055).powf(2.4)
        }
    };
    0.2126 * channel(rgb[0]) + 0.7152 * channel(rgb[1]) + 0.0722 * channel(rgb[2])
}

fn contrast(left: [u8; 3], right: [u8; 3]) -> f64 {
    let left = luminance(left);
    let right = luminance(right);
    (left.max(right) + 0.05) / (left.min(right) + 0.05)
}

fn ensure_contrast(value: &str, background: &str, floor: f64) -> Result<String, String> {
    let original = parse_rgb(value)?;
    let background = parse_rgb(background)?;
    if contrast(original, background) >= floor {
        return Ok(value.to_owned());
    }
    let target: [u8; 3] = if luminance(background) < 0.5 {
        [255, 255, 255]
    } else {
        [0, 0, 0]
    };
    for step in 1..=255_u16 {
        let blend = |channel: usize| {
            let from = u16::from(original[channel]);
            let to = u16::from(target[channel]);
            ((from * (255 - step) + to * step + 127) / 255) as u8
        };
        let candidate = [blend(0), blend(1), blend(2)];
        if contrast(candidate, background) >= floor {
            return Ok(format!(
                "#{:02x}{:02x}{:02x}",
                candidate[0], candidate[1], candidate[2]
            ));
        }
    }
    Err(format!("cannot adjust {value} to contrast {floor:.1}"))
}
