//! Generates `docs/keys.md` from the command registry and the default keymap.
//!
//! Run `cargo run --all-features --example generate-keys-doc` to refresh the
//! file, or pass `--check` to fail when the committed copy has drifted.
#[path = "common/keydoc.rs"]
mod keydoc;

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use snip::keys::Keymap;

const GENERATED: &str =
    "<!-- @generated by examples/generate-keys-doc.rs; do not edit by hand. -->\n";

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let check = env::args().skip(1).any(|argument| argument == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let path = root.join("docs/keys.md");
    let expected = render(&Keymap::defaults());

    if check {
        return match fs::read_to_string(&path) {
            Ok(actual) if actual == expected => Ok(()),
            Ok(actual) => Err(format!(
                "{} differs (disk {} bytes, generated {} bytes)",
                path.display(),
                actual.len(),
                expected.len()
            )),
            Err(error) => Err(format!("{} missing or unreadable: {error}", path.display())),
        };
    }

    fs::write(&path, expected).map_err(|error| format!("cannot write {}: {error}", path.display()))
}

fn render(keymap: &Keymap) -> String {
    let document = keydoc::collect(keymap);
    let mut out = String::from(GENERATED);
    out.push_str("\n# Key bindings\n\n");
    out.push_str(
        "Every row with an **Action** is rebindable in `keys.toml`; fixed inputs \
         such as `Ctrl-c`, digits, search editing, and mouse gestures are not. \
         Use the Action value as the key; run `snip keys path` to find \
         the file, `snip keys show <action>` to inspect one, and \
         `snip keys check` to validate your edits.\n\n\
         Bindings are grouped by *mode* — the context a key is live in. Normal \
         pane stacks include `global`, while exclusive modes expose only \
         the global actions in their inheritance allowlist. When several modes \
         are active, the narrower one wins.\n\n",
    );

    out.push_str("## Contents\n\n");
    for mode in &document.modes {
        let _ = writeln!(out, "- [{}](#{})", mode.label, anchor(mode.label));
    }
    out.push_str("- [Mouse](#mouse)\n\n");

    for mode in &document.modes {
        let _ = writeln!(out, "## {}\n", mode.label);
        let _ = writeln!(out, "{}\n", mode.blurb);
        if mode.rows.is_empty() {
            out.push_str("_No bindings of its own._\n\n");
        } else {
            out.push_str("| Key | Action | Description |\n| --- | --- | --- |\n");
            for row in &mode.rows {
                let keys = row
                    .keys
                    .iter()
                    .map(|key| format!("`{}`", escape(key)))
                    .collect::<Vec<_>>()
                    .join(" / ");
                let action = row
                    .action
                    .map_or_else(|| "—".to_owned(), |action| format!("`{action}`"));
                let _ = writeln!(out, "| {keys} | {action} | {} |", escape(row.description));
            }
            out.push('\n');
        }

        if !mode.inherited.is_empty() {
            out.push_str("### Inherited from `global`\n\n");
            out.push_str("| Key | Action | Description |\n| --- | --- | --- |\n");
            for row in &mode.inherited {
                let keys = row
                    .keys
                    .iter()
                    .map(|key| format!("`{}`", escape(key)))
                    .collect::<Vec<_>>()
                    .join(" / ");
                let _ = writeln!(
                    out,
                    "| {keys} | `{}` | {} |",
                    row.action.expect("inherited commands have action slugs"),
                    escape(row.description)
                );
            }
            out.push('\n');
        }
    }

    out.push_str("## Mouse\n\n");
    out.push_str("| Input | Description |\n| --- | --- |\n");
    for mouse in &document.mouse {
        let _ = writeln!(
            out,
            "| {} | {} (available in {}) |",
            escape(mouse.key),
            escape(mouse.description),
            mouse.modes.join(", ")
        );
    }
    out.push('\n');
    out
}

fn anchor(label: &str) -> String {
    label
        .chars()
        .filter(|character| character.is_ascii_alphanumeric() || *character == '-')
        .collect::<String>()
        .to_ascii_lowercase()
}

fn escape(value: &str) -> String {
    value.replace('|', "\\|").replace(['\r', '\n'], " ")
}
