#[allow(dead_code)]
#[path = "../src/cli.rs"]
mod cli;

use clap::CommandFactory;
use cli::Cli;
use std::collections::BTreeMap;
use std::env;
use std::error::Error;
use std::ffi::OsStr;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{self, Command};

type Result<T> = std::result::Result<T, Box<dyn Error>>;

enum Mode {
    Generate,
    Check,
    Preview(String),
}

#[derive(Default)]
struct Changes {
    missing: Vec<String>,
    changed: Vec<String>,
    extra: Vec<String>,
}

impl Changes {
    fn is_empty(&self) -> bool {
        self.missing.is_empty() && self.changed.is_empty() && self.extra.is_empty()
    }

    fn print(&self) {
        for name in &self.missing {
            eprintln!("missing: {name}");
        }
        for name in &self.changed {
            eprintln!("changed: {name}");
        }
        for name in &self.extra {
            eprintln!("extra: {name}");
        }
    }
}

fn main() {
    if let Err(error) = run() {
        eprintln!("generate-man: error: {error}");
        process::exit(1);
    }
}

fn run() -> Result<()> {
    let mode = parse_mode()?;
    if !cfg!(feature = "tui") {
        return Err(io::Error::other(
            "man pages describe the full command tree; rerun with `--all-features`",
        )
        .into());
    }

    let generated = tempfile::tempdir()?;
    generate_pages(Cli::command(), generated.path())?;
    let expected = read_pages(generated.path())?;
    if expected.is_empty() {
        return Err(io::Error::other(
            "clap_mangen produced no section 1 pages; refusing to continue",
        )
        .into());
    }

    match mode {
        Mode::Generate => sync_artifacts(&expected),
        Mode::Check => check_artifacts(&expected),
        Mode::Preview(page) => preview_page(generated.path(), &expected, &page),
    }
}

fn parse_mode() -> Result<Mode> {
    let mut args = env::args().skip(1);
    let mode = match args.next().as_deref() {
        None => Mode::Generate,
        Some("--check") => Mode::Check,
        Some("--preview") => Mode::Preview(args.next().unwrap_or_else(|| "snip".to_owned())),
        Some(argument) => {
            return Err(io::Error::other(format!(
                "unknown argument `{argument}`; expected `--check` or `--preview [PAGE]`"
            ))
            .into());
        }
    };

    if let Some(argument) = args.next() {
        return Err(io::Error::other(format!("unexpected argument `{argument}`")).into());
    }
    Ok(mode)
}

fn man_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("man")
}

fn generate_pages(mut command: clap::Command, directory: &Path) -> Result<()> {
    fn generate(command: clap::Command, directory: &Path, source: &str) -> Result<()> {
        for subcommand in command
            .get_subcommands()
            .filter(|subcommand| !subcommand.is_hide_set())
            .cloned()
        {
            generate(subcommand, directory, source)?;
        }
        clap_mangen::Man::new(command)
            .source(source)
            .generate_to(directory)?;
        Ok(())
    }

    command = command.disable_help_subcommand(true);
    command.build();
    let source = format!("snip {}", env!("CARGO_PKG_VERSION"));
    generate(command, directory, &source)
}

fn index_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("src/commands/man_pages.rs")
}

fn read_pages(directory: &Path) -> Result<BTreeMap<String, Vec<u8>>> {
    let mut pages = BTreeMap::new();
    if !directory.exists() {
        return Ok(pages);
    }

    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension() != Some(OsStr::new("1")) {
            continue;
        }
        if !entry.file_type()?.is_file() {
            return Err(io::Error::other(format!(
                "managed man page is not a regular file: {}",
                path.display()
            ))
            .into());
        }
        let name = entry
            .file_name()
            .into_string()
            .map_err(|_| io::Error::other("man page filename is not valid UTF-8"))?;
        pages.insert(name, fs::read(path)?);
    }
    Ok(pages)
}

fn changes(expected: &BTreeMap<String, Vec<u8>>, actual: &BTreeMap<String, Vec<u8>>) -> Changes {
    let mut changes = Changes::default();
    for (name, contents) in expected {
        match actual.get(name) {
            None => changes.missing.push(name.clone()),
            Some(actual_contents) if actual_contents != contents => {
                changes.changed.push(name.clone());
            }
            Some(_) => {}
        }
    }
    for name in actual.keys() {
        if !expected.contains_key(name) {
            changes.extra.push(name.clone());
        }
    }
    changes
}

fn render_index(pages: &BTreeMap<String, Vec<u8>>) -> Vec<u8> {
    let mut index = String::from(
        "// @generated by examples/generate-man.rs; do not edit by hand.\n\
         #[rustfmt::skip]\n\
         pub static PAGES: &[(&str, &[u8])] = &[\n",
    );
    for name in pages.keys() {
        index.push_str(&format!(
            "    (\"{name}\", include_bytes!(\"../../man/{name}\")),\n"
        ));
    }
    index.push_str("];\n");
    index.into_bytes()
}

fn sync_artifacts(expected: &BTreeMap<String, Vec<u8>>) -> Result<()> {
    let directory = man_dir();
    fs::create_dir_all(&directory)?;
    let actual = read_pages(&directory)?;
    let changes = changes(expected, &actual);

    for name in changes.missing.iter().chain(&changes.changed) {
        fs::write(directory.join(name), &expected[name])?;
    }
    for name in &changes.extra {
        fs::remove_file(directory.join(name))?;
    }

    let expected_index = render_index(expected);
    let index = index_path();
    let index_changed = fs::read(&index).ok().as_deref() != Some(expected_index.as_slice());
    if index_changed {
        fs::write(&index, expected_index)?;
    }

    if changes.is_empty() && !index_changed {
        println!(
            "man pages and embedded index are up to date ({} pages)",
            expected.len()
        );
    } else {
        println!(
            "updated man artifacts: {} pages written, {} removed, index {}",
            changes.missing.len() + changes.changed.len(),
            changes.extra.len(),
            if index_changed {
                "written"
            } else {
                "unchanged"
            }
        );
    }
    Ok(())
}

fn check_artifacts(expected: &BTreeMap<String, Vec<u8>>) -> Result<()> {
    let actual = read_pages(&man_dir())?;
    let changes = changes(expected, &actual);
    let expected_index = render_index(expected);
    let index = index_path();
    let actual_index = fs::read(&index);
    let index_changed = actual_index
        .as_ref()
        .is_ok_and(|contents| contents != &expected_index);
    let index_missing = actual_index
        .as_ref()
        .is_err_and(|error| error.kind() == io::ErrorKind::NotFound);
    if let Err(error) = &actual_index
        && error.kind() != io::ErrorKind::NotFound
    {
        return Err(io::Error::new(
            error.kind(),
            format!("cannot read generated index {}: {error}", index.display()),
        )
        .into());
    }

    if changes.is_empty() && !index_missing && !index_changed {
        println!(
            "man pages and embedded index are up to date ({} pages)",
            expected.len()
        );
        return Ok(());
    }

    changes.print();
    if index_missing {
        eprintln!("missing: {}", index.display());
    } else if index_changed {
        eprintln!("changed: {}", index.display());
    }
    Err(
        io::Error::other("generated man artifacts are stale; run the generator without `--check`")
            .into(),
    )
}

fn preview_page(generated_dir: &Path, pages: &BTreeMap<String, Vec<u8>>, page: &str) -> Result<()> {
    if page.is_empty()
        || !page
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
    {
        return Err(io::Error::other(format!("invalid page name `{page}`")).into());
    }

    let filename = format!("{page}.1");
    if !pages.contains_key(&filename) {
        return Err(io::Error::other(format!(
            "unknown page `{page}`; choose a generated page stem such as `snip` or `snip-create`"
        ))
        .into());
    }

    let path = generated_dir.join(filename).canonicalize()?;
    println!("previewing {}", path.display());
    let status = Command::new("man").arg(&path).status().map_err(|error| {
        if error.kind() == io::ErrorKind::NotFound {
            io::Error::new(
                error.kind(),
                format!(
                    "could not launch `man`; the generated page is {}",
                    path.display()
                ),
            )
        } else {
            error
        }
    })?;
    if !status.success() {
        return Err(io::Error::other(format!("`man` exited with status {status}")).into());
    }
    Ok(())
}
