//! Generates `docs/keys.md` from the command registry and the default keymap.
//!
//! Run `cargo run --all-features --example generate-keys-doc` to refresh the
//! file, or pass `--check` to fail when the committed copy has drifted.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use snip::keys::{Chord, Keymap, Mode, chord_sort_key};
use snip::tui::command::{self, CommandId};
use snip::tui::help::{EXTRAS, HelpExtraGroup};

const GENERATED: &str =
    "<!-- @generated by examples/generate-keys-doc.rs; do not edit by hand. -->\n";

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let check = env::args().skip(1).any(|argument| argument == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let path = root.join("docs/keys.md");
    let expected = render(&Keymap::defaults());

    if check {
        return match fs::read_to_string(&path) {
            Ok(actual) if actual == expected => Ok(()),
            Ok(actual) => Err(format!(
                "{} differs (disk {} bytes, generated {} bytes)",
                path.display(),
                actual.len(),
                expected.len()
            )),
            Err(error) => Err(format!("{} missing or unreadable: {error}", path.display())),
        };
    }

    fs::write(&path, expected).map_err(|error| format!("cannot write {}: {error}", path.display()))
}

fn render(keymap: &Keymap) -> String {
    let mut out = String::from(GENERATED);
    out.push_str("\n# Key bindings\n\n");
    out.push_str(
        "Every row with an **Action** is rebindable in `keys.toml`; fixed inputs \
         such as `Ctrl-c`, digits, search editing, and mouse gestures are not. \
         Use the Action value as the key; run `snip keys path` to find \
         the file, `snip keys show <action>` to inspect one, and \
         `snip keys check` to validate your edits.\n\n\
         Bindings are grouped by *mode* — the context a key is live in. Normal \
         pane stacks include `global`, while exclusive modes expose only \
         the global actions in their inheritance allowlist. When several modes \
         are active, the narrower one wins.\n\n",
    );

    out.push_str("## Contents\n\n");
    for mode in Mode::ALL {
        let _ = writeln!(
            out,
            "- [{}](#{})",
            mode_label(mode),
            anchor(&mode_label(mode))
        );
    }
    out.push_str("- [Mouse](#mouse)\n\n");

    for mode in Mode::ALL {
        let _ = writeln!(out, "## {}\n", mode_label(mode));
        let _ = writeln!(out, "{}\n", mode_blurb(mode));

        let mut rows: Vec<(Vec<Chord>, &'static str, &'static str)> = Vec::new();
        let mut by_command: BTreeMap<usize, (CommandId, Vec<Chord>)> = BTreeMap::new();
        for (chord, id) in keymap.bindings_for(mode) {
            let order = CommandId::ALL
                .iter()
                .position(|candidate| *candidate == id)
                .expect("every bound command is registered");
            by_command
                .entry(order)
                .or_insert_with(|| (id, Vec::new()))
                .1
                .push(chord);
        }
        for (_, (id, mut chords)) in by_command {
            chords.sort_by_key(|chord| chord_sort_key(*chord));
            let command = command::get(id);
            rows.push((chords, command.slug, command.description));
        }
        rows.sort_by(|left, right| {
            chord_sort_key(left.0[0])
                .cmp(&chord_sort_key(right.0[0]))
                .then(left.1.cmp(right.1))
        });

        let extras = EXTRAS
            .iter()
            .filter(|extra| extra.modes.contains(&mode))
            .collect::<Vec<_>>();

        if rows.is_empty() && extras.is_empty() {
            out.push_str("_No bindings of its own._\n\n");
        } else {
            out.push_str("| Key | Action | Description |\n| --- | --- | --- |\n");
            for (chords, slug, description) in &rows {
                let keys = chords
                    .iter()
                    .map(|chord| format!("`{}`", escape(&chord.display())))
                    .collect::<Vec<_>>()
                    .join(" / ");
                let _ = writeln!(out, "| {keys} | `{slug}` | {description} |");
            }
            for extra in &extras {
                let action = if extra.slug.is_empty() {
                    "—".to_owned()
                } else {
                    format!("`{}`", extra.slug)
                };
                let _ = writeln!(
                    out,
                    "| `{}` | {action} | {} |",
                    escape(extra.key),
                    escape(extra.description)
                );
            }
            out.push('\n');
        }

        let inherited = mode.inherits();
        if !inherited.is_empty() {
            out.push_str("### Inherited from `global`\n\n");
            out.push_str("| Key | Action | Description |\n| --- | --- | --- |\n");
            for id in inherited {
                let command = command::get(*id);
                let keys = keymap
                    .chords_for(&[Mode::Global], *id)
                    .iter()
                    .map(|chord| format!("`{}`", escape(&chord.display())))
                    .collect::<Vec<_>>()
                    .join(" / ");
                let _ = writeln!(
                    out,
                    "| {keys} | `{}` | {} |",
                    command.slug,
                    escape(command.description)
                );
            }
            out.push('\n');
        }
    }

    out.push_str("## Mouse\n\n");
    out.push_str("| Input | Description |\n| --- | --- |\n");
    for extra in EXTRAS
        .iter()
        .filter(|extra| extra.group == HelpExtraGroup::Mouse)
    {
        let modes = extra
            .modes
            .iter()
            .map(|mode| mode_label(*mode))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "| {} | {} (available in {modes}) |",
            escape(extra.key),
            escape(extra.description)
        );
    }
    out.push('\n');
    out
}

fn mode_label(mode: Mode) -> String {
    match mode {
        Mode::Global => "global",
        Mode::Sidebar => "sidebar",
        Mode::List => "list",
        Mode::Preview => "preview",
        Mode::Fragment => "fragment",
        Mode::FragmentGrab => "fragment-grab",
        Mode::Trash => "trash",
        Mode::Help => "help",
        Mode::Git => "git",
        Mode::Gist => "gist",
        Mode::Search => "search",
    }
    .to_owned()
}

fn mode_blurb(mode: Mode) -> &'static str {
    match mode {
        Mode::Global => {
            "Part of normal pane stacks; exclusive modes inherit only commands in their allowlist."
        }
        Mode::Sidebar => "Live while the library pane on the left has focus.",
        Mode::List => "Live while the snippet list has focus.",
        Mode::Preview => "Live while the preview pane has focus.",
        Mode::Fragment => "Live while the preview has focus and the fragment list is expanded.",
        Mode::FragmentGrab => "Live while a fragment is grabbed and waiting to be dropped.",
        Mode::Trash => "Live while the trash pane has focus. Takes over the keyboard.",
        Mode::Help => "Live while this help panel is open. Takes over the keyboard.",
        Mode::Git => "Live while the Git console is open. Takes over the keyboard.",
        Mode::Gist => "Live while the Gist panel is open. Takes over the keyboard.",
        Mode::Search => "Live while a search query is being typed. Takes over the keyboard.",
    }
}

fn anchor(label: &str) -> String {
    label
        .chars()
        .filter(|character| character.is_ascii_alphanumeric() || *character == '-')
        .collect::<String>()
        .to_ascii_lowercase()
}

fn escape(value: &str) -> String {
    value.replace('|', "\\|").replace(['\r', '\n'], " ")
}
